In [12]:
import json
import os, getpass
import pandas as pd
import nlpaf
from nlpaf import inferential_stats 
import pandas as pd
# Load the dataset
def _set_env(var: str):
    if not os.environ.get(var):
        os.environ[var] = getpass.getpass(f"{var}: ")

_set_env("OPENAI_API_KEY")
_set_env("LANGCHAIN_API_KEY")
_set_env("MISTRAL_API_KEY")
_set_env("TOGETHER_API_KEY")

os.environ["LANGCHAIN_TRACING_V2"] = "false"

#init_chat_model("meta-llama/Llama-3.2-3B-Instruct-Turbo", model_provider="together", temperature= 0.7)

In [ ]:
pip install seaborn

In [ ]:
with open("agentic_tools/prompts/criteria_scorer_desc.json", "r") as file:
    data = json.load(file)

#data

In [ ]:
#generated_file = "../../gitlab/ows-eo-kg/evaluation/samples/big_eval_new.csv"
generated_file = "../../gitlab/ows-eo-kg/evaluation/samples/answers_w_structured_context.csv"

import pandas as pd
generated_df = pd.read_csv(generated_file)

In [13]:
# init workflow
from agentic_tools.agents.evaluator_builder import ScoreCriteriaPerAnswerBuilder
from tqdm import tqdm
#generated_file = "../../gitlab/ows-eo-kg/evaluation/samples/big_eval_new.csv"
generated_file = "../../gitlab/ows-eo-kg/evaluation/samples/answers_w_structured_context.csv"

import pandas as pd
generated_df = pd.read_csv(generated_file)

def evaluate_answers_w_scores() -> pd.DataFrame:

    llm_full = "gpt-4.1-mini-2025-04-14"  # "mistral-medium"# "gpt-4o-mini-2024-07-18"


    all_res = []
    for i, row in tqdm(generated_df.iterrows(), total=len(generated_df)):
        answer_lst=[
            ("rag_answer", row["rag_answer"],  row["structured_context"]),
            ("zero_shot_answer", row["zero_shot_answer"], row["structured_context"]),
            ("rag_two_steps_answer", row["rag_two_steps_answer"], row["structured_context"])]


        validator_workflow = ScoreCriteriaPerAnswerBuilder(
            model_thread_id= "score_w_gpt4", 
            llm_name=llm_full,
            llm_num=1,
            experiment_name="score",
            temperature=0.7,
            answer_lst= answer_lst)
        
        q = row["question"]  # "Capital if France? "  #
        best = validator_workflow._invoke_graph(
            {"question": q}, id_=i)#.model_dump()  #["critical_questions"]
        
        
        rag_score = best['answer_scores_dict']["rag_answer"] 
        zero_shot_score = best['answer_scores_dict']["zero_shot_answer"] 
        rag_2score = best['answer_scores_dict']["rag_two_steps_answer"] 
        all_res.append({**row.to_dict(), "score_rag": rag_score,  "score_2rag": rag_2score, "score_zero_shot": zero_shot_score,
                        "score_is_rag_better": rag_score > zero_shot_score,
                        "score_is_2rag_better": rag_2score > zero_shot_score,
                        "score_instruction_template": best['instruction_template'],
                        "score_model" : llm_full,
                        **{f"score_2rag_criteria_{k}": v for k,v in best["answer_criteria_scores"]["rag_two_steps_answer"].items() },
                        **{f"score_rag_criteria_{k}": v for k,v in best["answer_criteria_scores"]["rag_answer"].items() },
                        **{f"score_0shot_criteria_{k}": v for k,v in best["answer_criteria_scores"]["zero_shot_answer"].items() }
                        
                        })
    def _apply_add_metadata(row):
        row["question_type"] = row["idx"].split("_")[-1]
        row["topic"] = "_".join(row["idx"].split("_")[:-1])
        return row

    scored_results = pd.DataFrame(all_res)
    scored_results = scored_results.apply(_apply_add_metadata, axis=1)
    return scored_results

scored_results = evaluate_answers_w_scores()

  3%|▎         | 4/140 [00:00<00:03, 35.41it/s]

Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 11%|█         | 15/140 [00:00<00:02, 44.07it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14

 14%|█▍        | 20/140 [00:00<00:02, 45.50it/s]

Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 21%|██        | 29/140 [00:00<00:03, 35.01it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14

 29%|██▉       | 41/140 [00:01<00:02, 43.06it/s]

Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 36%|███▋      | 51/140 [00:01<00:02, 44.21it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14

 44%|████▍     | 62/140 [00:01<00:01, 46.50it/s]

Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14

 48%|████▊     | 67/140 [00:01<00:01, 47.28it/s]

Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 56%|█████▋    | 79/140 [00:01<00:01, 49.22it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 64%|██████▍   | 90/140 [00:02<00:01, 42.44it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14

 73%|███████▎  | 102/140 [00:02<00:00, 46.81it/s]

Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 80%|████████  | 112/140 [00:02<00:00, 47.95it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 84%|████████▍ | 118/140 [00:02<00:00, 49.17it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow

 92%|█████████▏| 129/140 [00:02<00:00, 48.60it/s]

the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14

100%|██████████| 140/140 [00:03<00:00, 45.00it/s]

Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed
Initializing LLM gpt-4.1-mini-2025-04-14
Building Agentic Graph
building workflow
the call will be repeated 3 times
Building Completed!
run `display(Image(graph.get_graph(xray=1).draw_mermaid_png()))` to see your Agentic Graph
experiment name:  score
invoking
already assessed

In [14]:
scored_results.head()

,idx,model,temperature,question,aql_params,query,aql_results,context,rag_answer,zero_shot_answer,...,score_rag_criteria_groundedness,score_rag_criteria_helpfulness,score_rag_criteria_depth,score_0shot_criteria_factuality,score_0shot_criteria_relevance,score_0shot_criteria_groundedness,score_0shot_criteria_helpfulness,score_0shot_criteria_depth,question_type,topic
0,CLIMATE INDICATORS_Exploratory,mistral-small-2503,-1,"How do variations in cryospheric indicators, s...","{'n': 16, 'k': 3, 'k_threshold': 0.3, 's': 2}",cryospheric indicators AND glacier retreat AND...,[{'title': 'Rapid marine deglaciation: asynchr...,[Document(id='f2516234-7ed2-488a-b315-14b85e7a...,"Variations in cryospheric indicators, such as ...","Variations in cryospheric indicators, such as ...",...,4.00,5.00,5.00,5.0,5,5.00,5.00,5.00,Exploratory,CLIMATE INDICATORS
1,CLIMATE INDICATORS_Comparative,mistral-small-2503,-1,How do cryospheric indicators compare to land ...,"{'n': 16, 'k': 3, 'k_threshold': 0.3, 's': 2}",cryospheric indicators AND land surface indica...,[{'title': 'Surface Contribution to Planetary ...,[Document(id='df8584cd-0835-496c-98c1-22d326ab...,Cryospheric indicators and land surface/agricu...,Cryospheric indicators and land surface/agricu...,...,5.00,4.33,4.33,5.0,5,3.67,4.67,5.00,Comparative,CLIMATE INDICATORS
2,CLIMATE INDICATORS_Descriptive,mistral-small-2503,-1,What are cryospheric indicators and how do the...,"{'n': 16, 'k': 3, 'k_threshold': 0.3, 's': 2}",cryospheric indicators AND Earth's climate AND...,[{'title': 'Climates of the Earth and Cryosphe...,[Document(id='df8584cd-0835-496c-98c1-22d326ab...,### Answer\n\nCryospheric indicators are a set...,### Cryospheric Indicators and Their Influence...,...,5.00,5.00,4.67,5.0,5,4.67,5.00,5.00,Descriptive,CLIMATE INDICATORS
3,CLIMATE INDICATORS_Causal,mistral-small-2503,-1,How does the melting of glaciers and ice sheet...,"{'n': 16, 'k': 3, 'k_threshold': 0.3, 's': 2}",glacier melting AND ice sheet melting AND glob...,[{'title': 'Role of Snowfall Versus Air Temper...,[Document(id='593df856-6e7a-423c-a3f3-f3269761...,The melting of glaciers and ice sheets signifi...,The melting of glaciers and ice sheets signifi...,...,5.00,5.00,4.33,5.0,5,3.33,4.00,3.67,Causal,CLIMATE INDICATORS
4,CLIMATE INDICATORS_Relational,mistral-small-2503,-1,What is the relationship between cryospheric c...,"{'n': 16, 'k': 3, 'k_threshold': 0.3, 's': 2}",cryospheric changes AND glacier melt AND snow ...,[{'title': 'Carbon dynamics shift in changing ...,[Document(id='f589344e-b28d-42dc-9cff-b606a58d...,"The relationship between cryospheric changes, ...","The relationship between cryospheric changes, ...",...,3.67,4.67,4.67,5.0,5,4.67,5.00,5.00,Relational,CLIMATE INDICATORS

In [15]:
# scored_results.to_csv("output/evaluation/scoring_structured_context_results.csv", index= False)


evals = {
    # "init": "output/evaluation/scoring_init_results.csv",
    "w_structured_context": "output/evaluation/scoring_structured_context_results.csv"
}
analysis_per_experiment = {}
criteria_lst = [
        "score_rag_criteria_factuality",
        "score_2rag_criteria_factuality",
        "score_0shot_criteria_factuality",
        "score_2rag_criteria_relevance",
        "score_rag_criteria_relevance",
        "score_0shot_criteria_relevance",
        "score_2rag_criteria_groundedness",
        "score_rag_criteria_groundedness",
        "score_0shot_criteria_groundedness",
        "score_2rag_criteria_helpfulness",
        "score_rag_criteria_helpfulness",
        "score_0shot_criteria_helpfulness",
        "score_2rag_criteria_depth",
        "score_rag_criteria_depth",
        "score_0shot_criteria_depth",
    ]




eval_df = pd.read_csv(evals["w_structured_context"])

eval_df = eval_df[
    [
        "idx",
        "model",
        "question_type",
        "topic",
        "score_rag",
        "score_zero_shot",
        "score_2rag",
        "score_is_rag_better",
        "score_is_2rag_better",
        "score_instruction_template",
        "score_model",
        "score_rag_criteria_factuality",
        "score_rag_criteria_relevance",
        "score_rag_criteria_groundedness",
        "score_rag_criteria_helpfulness",
        "score_rag_criteria_depth",
        "score_0shot_criteria_factuality",
        "score_0shot_criteria_relevance",
        "score_0shot_criteria_groundedness",
        "score_0shot_criteria_helpfulness",
        "score_0shot_criteria_depth",
        "score_2rag_criteria_factuality",
        "score_2rag_criteria_relevance",
        "score_2rag_criteria_groundedness",
        "score_2rag_criteria_helpfulness",
        "score_2rag_criteria_depth",
    ]
]
desc_stats = {}
# Overall
desc_stats["overall_score"] = (
    eval_df.groupby("model")[["score_2rag", "score_rag", "score_zero_shot"]]
    .mean()
    .reset_index()
)

#  Criteria


desc_stats["criteria"] = (
    eval_df.groupby("model")[criteria_lst].mean().reset_index()
)

desc_stats["question_type"] = (
    eval_df.groupby(["model", "question_type"])[
        ["score_2rag", "score_rag", "score_zero_shot"]
    ]
    .mean()
    .reset_index()
)

desc_stats["topic"] = (
    eval_df.groupby(["model", "topic"])[
        ["score_2rag", "score_rag", "score_zero_shot"]
    ]
    .mean()
    .reset_index()
)

# --- 5. : how often RAG is better? ---
desc_stats["rag_better_ratio_df"] = (
    eval_df.groupby("model")["score_is_rag_better"]
    .mean()
    .reset_index()
    .rename(columns={"score_is_rag_better": "rag_better_ratio"})
)

desc_stats["2rag_better_ratio_df"] = (
    eval_df.groupby("model")["score_is_2rag_better"]
    .mean()
    .reset_index()
    .rename(columns={"score_is_2rag_better": "rag_better_ratio"})
)

In [16]:
desc_stats['overall_score']
# overall: RAG wins with MISTRAL

,model,score_2rag,score_rag,score_zero_shot
0,meta-llama/Llama-3.3-70B-Instruct-Turbo,4.889000,4.499286,4.634429
1,mistral-small-2503,4.947714,4.797857,4.713000

In [17]:
##





def flatten_scores(df_scores):
    # Flatten the scores
    flatten_lst = []

    for _, row in df_scores.iterrows():
        for score_col in ["score_2rag", "score_rag", "score_zero_shot"]:
            exp = score_col.replace("score_", "")
            flat_elt = {
                "topic": row["topic"],
                "question_type": row["question_type"],
                "model": row["model"],
                "score": row[score_col],
                "experiment": exp
            }

            criteria_sublist = [c for c in criteria_lst if c.find(f'_{exp.replace("zero_shot", "0shot")}_') > -1]
            for criteria_col in criteria_sublist:
                flat_elt[f"score_{criteria_col.split('_')[-1]}"] = row[criteria_col]
            flatten_lst.append(flat_elt)
    return pd.DataFrame(flatten_lst)

# Define factors and their group columns

scores_flat_df = flatten_scores(eval_df)  # 
scores_flat_df.to_csv("output/evaluation/scores_flat.csv", index=False)

In [ ]:
pip install -qU seaborn

In [19]:
print(scores_flat_df.head(2))

                topic question_type               model  score experiment  \
0  CLIMATE INDICATORS   Exploratory  mistral-small-2503   4.93       2rag
1  CLIMATE INDICATORS   Exploratory  mistral-small-2503   4.80        rag

   score_factuality  score_relevance  score_groundedness  score_helpfulness  \
0               5.0              5.0                4.67                5.0
1               5.0              5.0                4.00                5.0

   score_depth
0          5.0
1          5.0

In [21]:
import pandas as pd

df = scores_flat_df
# --- Scores to include ---
score_cols = ["score", "score_factuality", "score_relevance",
              "score_groundedness", "score_helpfulness", "score_depth"]

# --- Separate tables by model and aggregate mean ---
for model_name in df["model"].unique():
    df_model = (
        df[df["model"] == model_name]
        .groupby("experiment")[score_cols]
        .mean()
        .round(2)
    )

    latex_table = df_model.to_latex(index=True,
                                    caption=f"Mean scores per experiment for {model_name}",
                                    label=f"tab:{model_name.replace('-', '_')}",
                                    float_format="%.2f")
    print(f"% --- {model_name} ---")
    print(latex_table)
    print()

% --- mistral-small-2503 ---
\begin{table}
\caption{Mean scores per experiment for mistral-small-2503}
\label{tab:mistral_small_2503}
\begin{tabular}{lrrrrrr}
\toprule
 & score & score_factuality & score_relevance & score_groundedness & score_helpfulness & score_depth \\
experiment &  &  &  &  &  &  \\
\midrule
2rag & 4.95 & 5.00 & 5.00 & 4.80 & 5.00 & 4.96 \\
rag & 4.80 & 4.94 & 5.00 & 4.55 & 4.80 & 4.70 \\
zero_shot & 4.71 & 4.95 & 5.00 & 3.93 & 4.88 & 4.81 \\
\bottomrule
\end{tabular}
\end{table}


% --- meta-llama/Llama-3.3-70B-Instruct-Turbo ---
\begin{table}
\caption{Mean scores per experiment for meta-llama/Llama-3.3-70B-Instruct-Turbo}
\label{tab:meta_llama/Llama_3.3_70B_Instruct_Turbo}
\begin{tabular}{lrrrrrr}
\toprule
 & score & score_factuality & score_relevance & score_groundedness & score_helpfulness & score_depth \\
experiment &  &  &  &  &  &  \\
\midrule
2rag & 4.89 & 4.97 & 4.98 & 4.63 & 4.95 & 4.92 \\
rag & 4.50 & 4.83 & 5.00 & 4.24 & 4.33 & 4.10 \\
zero_shot & 4.63 & 4.90 & 5.00 & 3.83 & 4.77 & 4.68 \\
\bottomrule
\end{tabular}
\end{table}

In [22]:
2850 +  47883 + 2021267 + 3599

2075599